# Generated by Django 2.0 on 2020-12-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='sociallink',
            field=models.CharField(default='facebook.com', max_length=250),
        ),
        migrations.AddField(
            model_name='chef',
            name='weblink',
            field=models.CharField(default='abc@.com', max_length=250),
        ),
        migrations.AddField(
            model_name='chef',
            name='zipcode',
            field=models.BigIntegerField(default=123),
        ),
        migrations.AddField(
            model_name='customer',
            name='sociallink',
            field=models.CharField(default='facebook.com', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='weblink',
            field=models.CharField(default='abc@.com', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.BigIntegerField(default=123),
        ),
    ]
