# Generated by Django 2.0 on 2020-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201217_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='ProductDescription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(default='aa', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BigIntegerField(default=5),
        ),
    ]
