# Generated by Django 2.0 on 2020-12-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201222_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Expirydate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='Mfgdate',
            field=models.CharField(max_length=50),
        ),
    ]
