# Generated by Django 2.0 on 2020-12-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201222_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chef_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Chef'),
        ),
    ]
