# Generated by Django 2.0 on 2020-12-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_chef_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chef_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Chef'),
        ),
    ]
