# Generated by Django 2.0 on 2021-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201231_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
